spring:
  application:
    name: DGE Demo
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:dgechatdb}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080



logging:
  level:
    root: INFO
    org.dge.demo: DEBUG

chat:
  api:
    key: ${API_KEY:my-secret-key-dge-123}


bucket4j:
  enabled: true
  filters:
    - cache-name: bucket4j-dge-cache
      url: /.*
      http-response-body: "{'status' : 'Rate limit exceeded. Try again later.'}"
      rate-limits:
        - expression: 1
          bandwidths:
            - capacity: 100
              time: 1
              unit: minutes
              refill-speed: intervally
